name: Precompile Check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-precompile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run precompile
        run: npm run precompile
      - name: Check for changes
        run: |
          if [[ -n $(git diff --name-only) ]]; then
            echo "The following files have changed:"
            git diff --name-only
            echo ""
            echo "Diff:"
            git diff
            echo ""
            echo "::error:: properties-generated.ts is not in sync. Either the file has been modified manually or it has not been regenerated. Run 'npm run precompile' to regenerate them."
            exit 1
          fi
